// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7J6Ebt2BfdR_Z7amnute0Rka_eLjP9KQ',
    appId: '1:792195229692:web:7ac1756229e3c839f23479',
    messagingSenderId: '792195229692',
    projectId: 'flowpluschat',
    authDomain: 'flowpluschat.firebaseapp.com',
    storageBucket: 'flowpluschat.firebasestorage.app',
    measurementId: 'G-PYQJHQPLB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdNVS1sJpDr4AxVvhpvx4smkA01TzDl8s',
    appId: '1:792195229692:android:9b6bec54d859a8e9f23479',
    messagingSenderId: '792195229692',
    projectId: 'flowpluschat',
    storageBucket: 'flowpluschat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-qgTuFI1ZMoz70nYfWKgKc3L8Q_9Tk_I',
    appId: '1:792195229692:ios:6e0edcc38a779f4df23479',
    messagingSenderId: '792195229692',
    projectId: 'flowpluschat',
    storageBucket: 'flowpluschat.firebasestorage.app',
    iosBundleId: 'com.example.magmentv101',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-qgTuFI1ZMoz70nYfWKgKc3L8Q_9Tk_I',
    appId: '1:792195229692:ios:6e0edcc38a779f4df23479',
    messagingSenderId: '792195229692',
    projectId: 'flowpluschat',
    storageBucket: 'flowpluschat.firebasestorage.app',
    iosBundleId: 'com.example.magmentv101',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7J6Ebt2BfdR_Z7amnute0Rka_eLjP9KQ',
    appId: '1:792195229692:web:9fd33215adb63706f23479',
    messagingSenderId: '792195229692',
    projectId: 'flowpluschat',
    authDomain: 'flowpluschat.firebaseapp.com',
    storageBucket: 'flowpluschat.firebasestorage.app',
    measurementId: 'G-WXSL7XNB1N',
  );
}
